// AUTO-GENERATED by scripts/generate-protocol-map.mjs — do not edit manually.
// Source: runtime/codex-upstream/codex-rs/app-server-protocol/src/protocol/common.rs

import type {
    AccountLoginCompletedNotification,
    AccountRateLimitsUpdatedNotification,
    AccountUpdatedNotification,
    AgentMessageDeltaNotification,
    AppListUpdatedNotification,
    ApplyPatchApprovalParams,
    ApplyPatchApprovalResponse,
    AppsListParams,
    AppsListResponse,
    CancelLoginAccountParams,
    CancelLoginAccountResponse,
    ChatgptAuthTokensRefreshParams,
    ChatgptAuthTokensRefreshResponse,
    CommandExecOutputDeltaNotification,
    CommandExecParams,
    CommandExecResizeParams,
    CommandExecResizeResponse,
    CommandExecResponse,
    CommandExecTerminateParams,
    CommandExecTerminateResponse,
    CommandExecWriteParams,
    CommandExecWriteResponse,
    CommandExecutionOutputDeltaNotification,
    CommandExecutionRequestApprovalParams,
    CommandExecutionRequestApprovalResponse,
    ConfigBatchWriteParams,
    ConfigReadParams,
    ConfigReadResponse,
    ConfigRequirementsReadResponse,
    ConfigValueWriteParams,
    ConfigWarningNotification,
    ConfigWriteResponse,
    ContextCompactedNotification,
    DeprecationNoticeNotification,
    DynamicToolCallParams,
    DynamicToolCallResponse,
    ErrorNotification,
    ExecCommandApprovalParams,
    ExecCommandApprovalResponse,
    ExperimentalFeatureEnablementSetParams,
    ExperimentalFeatureEnablementSetResponse,
    ExperimentalFeatureListParams,
    ExperimentalFeatureListResponse,
    ExternalAgentConfigDetectParams,
    ExternalAgentConfigDetectResponse,
    ExternalAgentConfigImportParams,
    ExternalAgentConfigImportResponse,
    FeedbackUploadParams,
    FeedbackUploadResponse,
    FileChangeOutputDeltaNotification,
    FileChangeRequestApprovalParams,
    FileChangeRequestApprovalResponse,
    FsChangedNotification,
    FsCopyParams,
    FsCopyResponse,
    FsCreateDirectoryParams,
    FsCreateDirectoryResponse,
    FsGetMetadataParams,
    FsGetMetadataResponse,
    FsReadDirectoryParams,
    FsReadDirectoryResponse,
    FsReadFileParams,
    FsReadFileResponse,
    FsRemoveParams,
    FsRemoveResponse,
    FsUnwatchParams,
    FsUnwatchResponse,
    FsWatchParams,
    FsWatchResponse,
    FsWriteFileParams,
    FsWriteFileResponse,
    FuzzyFileSearchParams,
    FuzzyFileSearchResponse,
    FuzzyFileSearchSessionCompletedNotification,
    FuzzyFileSearchSessionUpdatedNotification,
    GetAccountParams,
    GetAccountRateLimitsResponse,
    GetAccountResponse,
    GetAuthStatusParams,
    GetAuthStatusResponse,
    GetConversationSummaryParams,
    GetConversationSummaryResponse,
    GitDiffToRemoteParams,
    GitDiffToRemoteResponse,
    HookCompletedNotification,
    HookStartedNotification,
    InitializeParams,
    InitializeResponse,
    ItemCompletedNotification,
    ItemGuardianApprovalReviewCompletedNotification,
    ItemGuardianApprovalReviewStartedNotification,
    ItemStartedNotification,
    ListMcpServerStatusParams,
    ListMcpServerStatusResponse,
    LoginAccountParams,
    LoginAccountResponse,
    LogoutAccountResponse,
    McpResourceReadParams,
    McpResourceReadResponse,
    McpServerElicitationRequestParams,
    McpServerElicitationRequestResponse,
    McpServerOauthLoginCompletedNotification,
    McpServerOauthLoginParams,
    McpServerOauthLoginResponse,
    McpServerRefreshResponse,
    McpServerStatusUpdatedNotification,
    McpToolCallProgressNotification,
    ModelListParams,
    ModelListResponse,
    ModelReroutedNotification,
    PermissionsRequestApprovalParams,
    PermissionsRequestApprovalResponse,
    PlanDeltaNotification,
    PluginInstallParams,
    PluginInstallResponse,
    PluginListParams,
    PluginListResponse,
    PluginReadParams,
    PluginReadResponse,
    PluginUninstallParams,
    PluginUninstallResponse,
    RawResponseItemCompletedNotification,
    ReasoningSummaryPartAddedNotification,
    ReasoningSummaryTextDeltaNotification,
    ReasoningTextDeltaNotification,
    ReviewStartParams,
    ReviewStartResponse,
    ServerRequestResolvedNotification,
    SkillsChangedNotification,
    SkillsConfigWriteParams,
    SkillsConfigWriteResponse,
    SkillsListParams,
    SkillsListResponse,
    TerminalInteractionNotification,
    ThreadArchiveParams,
    ThreadArchiveResponse,
    ThreadArchivedNotification,
    ThreadClosedNotification,
    ThreadCompactStartParams,
    ThreadCompactStartResponse,
    ThreadForkParams,
    ThreadForkResponse,
    ThreadListParams,
    ThreadListResponse,
    ThreadLoadedListParams,
    ThreadLoadedListResponse,
    ThreadMetadataUpdateParams,
    ThreadMetadataUpdateResponse,
    ThreadNameUpdatedNotification,
    ThreadReadParams,
    ThreadReadResponse,
    ThreadRealtimeClosedNotification,
    ThreadRealtimeErrorNotification,
    ThreadRealtimeItemAddedNotification,
    ThreadRealtimeOutputAudioDeltaNotification,
    ThreadRealtimeSdpNotification,
    ThreadRealtimeStartedNotification,
    ThreadRealtimeTranscriptUpdatedNotification,
    ThreadResumeParams,
    ThreadResumeResponse,
    ThreadRollbackParams,
    ThreadRollbackResponse,
    ThreadSetNameParams,
    ThreadSetNameResponse,
    ThreadShellCommandParams,
    ThreadShellCommandResponse,
    ThreadStartParams,
    ThreadStartResponse,
    ThreadStartedNotification,
    ThreadStatusChangedNotification,
    ThreadTokenUsageUpdatedNotification,
    ThreadUnarchiveParams,
    ThreadUnarchiveResponse,
    ThreadUnarchivedNotification,
    ThreadUnsubscribeParams,
    ThreadUnsubscribeResponse,
    ToolRequestUserInputParams,
    ToolRequestUserInputResponse,
    TurnCompletedNotification,
    TurnDiffUpdatedNotification,
    TurnInterruptParams,
    TurnInterruptResponse,
    TurnPlanUpdatedNotification,
    TurnStartParams,
    TurnStartResponse,
    TurnStartedNotification,
    TurnSteerParams,
    TurnSteerResponse,
    WindowsSandboxSetupCompletedNotification,
    WindowsSandboxSetupStartParams,
    WindowsSandboxSetupStartResponse,
    WindowsWorldWritableWarningNotification,
} from '@tjfontaine/codex-protocol-types';

/** Maps client → server request method strings to their params and response types. */
export interface ClientRequestMap {
    'initialize': { params: InitializeParams; response: InitializeResponse };
    'thread/start': { params: ThreadStartParams; response: ThreadStartResponse };
    'thread/resume': { params: ThreadResumeParams; response: ThreadResumeResponse };
    'thread/fork': { params: ThreadForkParams; response: ThreadForkResponse };
    'thread/archive': { params: ThreadArchiveParams; response: ThreadArchiveResponse };
    'thread/unsubscribe': { params: ThreadUnsubscribeParams; response: ThreadUnsubscribeResponse };
    'thread/name/set': { params: ThreadSetNameParams; response: ThreadSetNameResponse };
    'thread/metadata/update': { params: ThreadMetadataUpdateParams; response: ThreadMetadataUpdateResponse };
    'thread/unarchive': { params: ThreadUnarchiveParams; response: ThreadUnarchiveResponse };
    'thread/compact/start': { params: ThreadCompactStartParams; response: ThreadCompactStartResponse };
    'thread/shellCommand': { params: ThreadShellCommandParams; response: ThreadShellCommandResponse };
    'thread/rollback': { params: ThreadRollbackParams; response: ThreadRollbackResponse };
    'thread/list': { params: ThreadListParams; response: ThreadListResponse };
    'thread/loaded/list': { params: ThreadLoadedListParams; response: ThreadLoadedListResponse };
    'thread/read': { params: ThreadReadParams; response: ThreadReadResponse };
    'skills/list': { params: SkillsListParams; response: SkillsListResponse };
    'plugin/list': { params: PluginListParams; response: PluginListResponse };
    'plugin/read': { params: PluginReadParams; response: PluginReadResponse };
    'app/list': { params: AppsListParams; response: AppsListResponse };
    'fs/readFile': { params: FsReadFileParams; response: FsReadFileResponse };
    'fs/writeFile': { params: FsWriteFileParams; response: FsWriteFileResponse };
    'fs/createDirectory': { params: FsCreateDirectoryParams; response: FsCreateDirectoryResponse };
    'fs/getMetadata': { params: FsGetMetadataParams; response: FsGetMetadataResponse };
    'fs/readDirectory': { params: FsReadDirectoryParams; response: FsReadDirectoryResponse };
    'fs/remove': { params: FsRemoveParams; response: FsRemoveResponse };
    'fs/copy': { params: FsCopyParams; response: FsCopyResponse };
    'fs/watch': { params: FsWatchParams; response: FsWatchResponse };
    'fs/unwatch': { params: FsUnwatchParams; response: FsUnwatchResponse };
    'skills/config/write': { params: SkillsConfigWriteParams; response: SkillsConfigWriteResponse };
    'plugin/install': { params: PluginInstallParams; response: PluginInstallResponse };
    'plugin/uninstall': { params: PluginUninstallParams; response: PluginUninstallResponse };
    'turn/start': { params: TurnStartParams; response: TurnStartResponse };
    'turn/steer': { params: TurnSteerParams; response: TurnSteerResponse };
    'turn/interrupt': { params: TurnInterruptParams; response: TurnInterruptResponse };
    'review/start': { params: ReviewStartParams; response: ReviewStartResponse };
    'model/list': { params: ModelListParams; response: ModelListResponse };
    'experimentalFeature/list': { params: ExperimentalFeatureListParams; response: ExperimentalFeatureListResponse };
    'experimentalFeature/enablement/set': { params: ExperimentalFeatureEnablementSetParams; response: ExperimentalFeatureEnablementSetResponse };
    'mcpServer/oauth/login': { params: McpServerOauthLoginParams; response: McpServerOauthLoginResponse };
    'config/mcpServer/reload': { params: Record<string, never>; response: McpServerRefreshResponse };
    'mcpServerStatus/list': { params: ListMcpServerStatusParams; response: ListMcpServerStatusResponse };
    'mcpServer/resource/read': { params: McpResourceReadParams; response: McpResourceReadResponse };
    'windowsSandbox/setupStart': { params: WindowsSandboxSetupStartParams; response: WindowsSandboxSetupStartResponse };
    'account/login/start': { params: LoginAccountParams; response: LoginAccountResponse };
    'account/login/cancel': { params: CancelLoginAccountParams; response: CancelLoginAccountResponse };
    'account/logout': { params: Record<string, never>; response: LogoutAccountResponse };
    'account/rateLimits/read': { params: Record<string, never>; response: GetAccountRateLimitsResponse };
    'feedback/upload': { params: FeedbackUploadParams; response: FeedbackUploadResponse };
    'command/exec': { params: CommandExecParams; response: CommandExecResponse };
    'command/exec/write': { params: CommandExecWriteParams; response: CommandExecWriteResponse };
    'command/exec/terminate': { params: CommandExecTerminateParams; response: CommandExecTerminateResponse };
    'command/exec/resize': { params: CommandExecResizeParams; response: CommandExecResizeResponse };
    'config/read': { params: ConfigReadParams; response: ConfigReadResponse };
    'externalAgentConfig/detect': { params: ExternalAgentConfigDetectParams; response: ExternalAgentConfigDetectResponse };
    'externalAgentConfig/import': { params: ExternalAgentConfigImportParams; response: ExternalAgentConfigImportResponse };
    'config/value/write': { params: ConfigValueWriteParams; response: ConfigWriteResponse };
    'config/batchWrite': { params: ConfigBatchWriteParams; response: ConfigWriteResponse };
    'configRequirements/read': { params: Record<string, never>; response: ConfigRequirementsReadResponse };
    'account/read': { params: GetAccountParams; response: GetAccountResponse };
    'getConversationSummary': { params: GetConversationSummaryParams; response: GetConversationSummaryResponse };
    'gitDiffToRemote': { params: GitDiffToRemoteParams; response: GitDiffToRemoteResponse };
    'getAuthStatus': { params: GetAuthStatusParams; response: GetAuthStatusResponse };
    'fuzzyFileSearch': { params: FuzzyFileSearchParams; response: FuzzyFileSearchResponse };
}

/** Union of all valid client → server request method strings. */
export type ClientMethod = keyof ClientRequestMap;

/** Maps server → client request method strings to their params and response types. */
export interface ServerRequestMap {
    'item/commandExecution/requestApproval': { params: CommandExecutionRequestApprovalParams; response: CommandExecutionRequestApprovalResponse };
    'item/fileChange/requestApproval': { params: FileChangeRequestApprovalParams; response: FileChangeRequestApprovalResponse };
    'item/tool/requestUserInput': { params: ToolRequestUserInputParams; response: ToolRequestUserInputResponse };
    'mcpServer/elicitation/request': { params: McpServerElicitationRequestParams; response: McpServerElicitationRequestResponse };
    'item/permissions/requestApproval': { params: PermissionsRequestApprovalParams; response: PermissionsRequestApprovalResponse };
    'item/tool/call': { params: DynamicToolCallParams; response: DynamicToolCallResponse };
    'account/chatgptAuthTokens/refresh': { params: ChatgptAuthTokensRefreshParams; response: ChatgptAuthTokensRefreshResponse };
    'applyPatchApproval': { params: ApplyPatchApprovalParams; response: ApplyPatchApprovalResponse };
    'execCommandApproval': { params: ExecCommandApprovalParams; response: ExecCommandApprovalResponse };
}

/** Maps server → client notification method strings to their payload types. */
export interface ServerNotificationMap {
    'error': ErrorNotification;
    'thread/started': ThreadStartedNotification;
    'thread/status/changed': ThreadStatusChangedNotification;
    'thread/archived': ThreadArchivedNotification;
    'thread/unarchived': ThreadUnarchivedNotification;
    'thread/closed': ThreadClosedNotification;
    'skills/changed': SkillsChangedNotification;
    'thread/name/updated': ThreadNameUpdatedNotification;
    'thread/tokenUsage/updated': ThreadTokenUsageUpdatedNotification;
    'turn/started': TurnStartedNotification;
    'hook/started': HookStartedNotification;
    'turn/completed': TurnCompletedNotification;
    'hook/completed': HookCompletedNotification;
    'turn/diff/updated': TurnDiffUpdatedNotification;
    'turn/plan/updated': TurnPlanUpdatedNotification;
    'item/started': ItemStartedNotification;
    'item/autoApprovalReview/started': ItemGuardianApprovalReviewStartedNotification;
    'item/autoApprovalReview/completed': ItemGuardianApprovalReviewCompletedNotification;
    'item/completed': ItemCompletedNotification;
    'rawResponseItem/completed': RawResponseItemCompletedNotification;
    'item/agentMessage/delta': AgentMessageDeltaNotification;
    'item/plan/delta': PlanDeltaNotification;
    'command/exec/outputDelta': CommandExecOutputDeltaNotification;
    'item/commandExecution/outputDelta': CommandExecutionOutputDeltaNotification;
    'item/commandExecution/terminalInteraction': TerminalInteractionNotification;
    'item/fileChange/outputDelta': FileChangeOutputDeltaNotification;
    'serverRequest/resolved': ServerRequestResolvedNotification;
    'item/mcpToolCall/progress': McpToolCallProgressNotification;
    'mcpServer/oauthLogin/completed': McpServerOauthLoginCompletedNotification;
    'mcpServer/startupStatus/updated': McpServerStatusUpdatedNotification;
    'account/updated': AccountUpdatedNotification;
    'account/rateLimits/updated': AccountRateLimitsUpdatedNotification;
    'app/list/updated': AppListUpdatedNotification;
    'fs/changed': FsChangedNotification;
    'item/reasoning/summaryTextDelta': ReasoningSummaryTextDeltaNotification;
    'item/reasoning/summaryPartAdded': ReasoningSummaryPartAddedNotification;
    'item/reasoning/textDelta': ReasoningTextDeltaNotification;
    'thread/compacted': ContextCompactedNotification;
    'model/rerouted': ModelReroutedNotification;
    'deprecationNotice': DeprecationNoticeNotification;
    'configWarning': ConfigWarningNotification;
    'fuzzyFileSearch/sessionUpdated': FuzzyFileSearchSessionUpdatedNotification;
    'fuzzyFileSearch/sessionCompleted': FuzzyFileSearchSessionCompletedNotification;
    'thread/realtime/started': ThreadRealtimeStartedNotification;
    'thread/realtime/itemAdded': ThreadRealtimeItemAddedNotification;
    'thread/realtime/transcriptUpdated': ThreadRealtimeTranscriptUpdatedNotification;
    'thread/realtime/outputAudio/delta': ThreadRealtimeOutputAudioDeltaNotification;
    'thread/realtime/sdp': ThreadRealtimeSdpNotification;
    'thread/realtime/error': ThreadRealtimeErrorNotification;
    'thread/realtime/closed': ThreadRealtimeClosedNotification;
    'windows/worldWritableWarning': WindowsWorldWritableWarningNotification;
    'windowsSandbox/setupCompleted': WindowsSandboxSetupCompletedNotification;
    'account/login/completed': AccountLoginCompletedNotification;
}

