//! Stub module — v8 runtime replaced by wasi-js-engine for wasip2.
//! Auto-generated by codex-codemod. Do not edit.

use std::collections::HashMap;
use serde_json::Value as JsonValue;
use tokio::sync::mpsc;
use crate::description::ToolDefinition;
use crate::response::FunctionCallOutputContentItem;

// Bring in rquickjs from our shim engine
use wasi_js_engine::rquickjs::{AsyncRuntime, AsyncContext, CatchResultExt, Value};

pub const DEFAULT_EXEC_YIELD_TIME_MS: u64 = 10_000;
pub const DEFAULT_WAIT_YIELD_TIME_MS: u64 = 10_000;
pub const DEFAULT_MAX_OUTPUT_TOKENS_PER_EXEC_CALL: usize = 10_000;

#[derive(Clone, Debug)]
pub struct ExecuteRequest {
    pub tool_call_id: String,
    pub enabled_tools: Vec<ToolDefinition>,
    pub source: String,
    pub stored_values: HashMap<String, JsonValue>,
    pub yield_time_ms: Option<u64>,
    pub max_output_tokens: Option<usize>,
}

#[derive(Clone, Debug)]
pub struct WaitRequest {
    pub cell_id: String,
    pub yield_time_ms: u64,
    pub terminate: bool,
}

#[derive(Debug, PartialEq)]
pub enum RuntimeResponse {
    Yielded {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
    },
    Terminated {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
    },
    Result {
        cell_id: String,
        content_items: Vec<FunctionCallOutputContentItem>,
        stored_values: HashMap<String, JsonValue>,
        error_text: Option<String>,
    },
}

#[derive(Debug)]
pub(crate) enum TurnMessage {
    ToolCall {
        cell_id: String,
        id: String,
        name: String,
        input: Option<JsonValue>,
    },
    Notify {
        cell_id: String,
        call_id: String,
        text: String,
    },
}

#[derive(Debug)]
pub(crate) enum RuntimeCommand {
    ToolResponse { id: String, result: JsonValue },
    ToolError { id: String, error_text: String },
    Terminate,
}

#[derive(Debug)]
pub(crate) enum RuntimeEvent {
    Started,
    ContentItem(FunctionCallOutputContentItem),
    YieldRequested,
    ToolCall {
        id: String,
        name: String,
        input: Option<JsonValue>,
    },
    Notify {
        call_id: String,
        text: String,
    },
    Result {
        stored_values: HashMap<String, JsonValue>,
        error_text: Option<String>,
    },
}

#[derive(Clone)]
pub(crate) struct RuntimeHandle {
}

impl RuntimeHandle {
    pub fn terminate_execution(&self) {}
}

pub(crate) fn spawn_runtime(
    request: ExecuteRequest,
    event_tx: mpsc::UnboundedSender<RuntimeEvent>,
) -> Result<(std::sync::mpsc::Sender<RuntimeCommand>, RuntimeHandle), String> {
    let (cmd_tx, _cmd_rx) = std::sync::mpsc::channel::<RuntimeCommand>();
    
    // Spawn a tokio task that runs rquickjs purely for execution
    tokio::spawn(async move {
        let _ = event_tx.send(RuntimeEvent::Started);
        
        let rt = match AsyncRuntime::new() {
            Ok(rt) => rt,
            Err(e) => {
                let _ = event_tx.send(RuntimeEvent::Result {
                    stored_values: request.stored_values,
                    error_text: Some(format!("Failed to create JS runtime: {}", e)),
                });
                return;
            }
        };

        let ctx = match AsyncContext::full(&rt).await {
            Ok(c) => c,
            Err(e) => {
                let _ = event_tx.send(RuntimeEvent::Result {
                    stored_values: request.stored_values,
                    error_text: Some(format!("Failed to create JS context: {}", e)),
                });
                return;
            }
        };
        
        ctx.with(|ctx| {
            let source = request.source.clone();
            let result = ctx.eval::<(), _>(source.as_str()).catch(&ctx);
            
            match result {
                Ok(_) => {
                    let _ = event_tx.send(RuntimeEvent::Result {
                        stored_values: request.stored_values,
                        error_text: None,
                    });
                }
                Err(e) => {
                    let _ = event_tx.send(RuntimeEvent::Result {
                        stored_values: request.stored_values,
                        error_text: Some(format!("JS error: {:?}", e)),
                    });
                }
            }
        }).await;
    });

    Ok((cmd_tx, RuntimeHandle {}))
}
