//! Robust transform types for the codex codemod.
//!
//! Each transform is self-describing, idempotent, and reports when
//! its target pattern doesn't match (upstream may have changed).

use std::path::Path;

/// Result of applying a single transform to a file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransformResult {
    /// The transform matched and was applied.
    Applied,
    /// The transform was already applied (idempotency guard).
    AlreadyApplied,
    /// The target pattern was not found in the file.
    NotMatched,
    /// The file path did not match this transform.
    PathNotMatched,
}

/// A single source transform.
pub enum Transform {
    /// Replace entire file content. Always idempotent (overwrites).
    ReplaceFile {
        /// Path suffix matching the end of the file path (component-aware).
        path_suffix: &'static str,
        content: &'static str,
    },

    /// Replace file with empty stub. Always idempotent.
    StubModule {
        /// Exact file name to match.
        file_name: &'static str,
    },

    /// Targeted string replacement: replace the FIRST occurrence only.
    ReplaceFirst {
        path_suffix: &'static str,
        find: &'static str,
        replace: &'static str,
    },

    /// Replace ALL occurrences of a string in a specific file.
    /// Use sparingly — only when all occurrences must change.
    ReplaceAll {
        path_suffix: &'static str,
        find: &'static str,
        replace: &'static str,
    },

    /// Prepend text to a file (if not already present).
    Prepend {
        path_suffix: &'static str,
        text: &'static str,
    },

    /// Comment out lines matching given prefixes.
    CommentOutLines {
        path_suffix: &'static str,
        prefixes: &'static [&'static str],
    },

    /// Global transform applied to ALL .rs files.
    /// Receives the file path so file-specific logic can be applied.
    Global {
        name: &'static str,
        apply: fn(&str, Option<&std::path::Path>) -> String,
    },
}

impl Transform {
    /// Check if this transform targets a specific file path.
    pub fn matches_path(&self, path: &Path) -> bool {
        match self {
            Transform::ReplaceFile { path_suffix, .. } => path_matches(path, path_suffix),
            Transform::StubModule { file_name } => {
                path.file_name().and_then(|f| f.to_str()) == Some(file_name)
            }
            Transform::ReplaceFirst { path_suffix, .. } => path_matches(path, path_suffix),
            Transform::ReplaceAll { path_suffix, .. } => path_matches(path, path_suffix),
            Transform::Prepend { path_suffix, .. } => path_matches(path, path_suffix),
            Transform::CommentOutLines { path_suffix, .. } => path_matches(path, path_suffix),
            Transform::Global { .. } => true, // Applies to all files
        }
    }

    /// Apply this transform to file content. Returns (new_content, result).
    ///
    /// For ReplaceFile and StubModule, returns the replacement content directly.
    /// For content transforms, modifies the content in place.
    pub fn apply(&self, content: &str) -> (String, TransformResult) {
        match self {
            Transform::ReplaceFile { content: new, .. } => {
                (new.to_string(), TransformResult::Applied)
            }

            Transform::StubModule { .. } => {
                let stub =
                    "//! Stub module — original platform-specific code stripped for wasip2.\n\
                            //! Auto-generated by codex-codemod. Do not edit.\n";
                (stub.to_string(), TransformResult::Applied)
            }

            Transform::ReplaceFirst { find, replace, .. } => {
                // Idempotency: if the replacement text is already present, skip.
                // Check this FIRST, because the replacement may contain the find text
                // (e.g., injecting stubs before #[cfg(test)] where replacement also ends with #[cfg(test)]).
                if content.contains(*replace) {
                    return (content.to_string(), TransformResult::AlreadyApplied);
                }
                if !content.contains(*find) {
                    return (content.to_string(), TransformResult::NotMatched);
                }
                // Replace only the first occurrence
                let result = content.replacen(*find, *replace, 1);
                (result, TransformResult::Applied)
            }

            Transform::ReplaceAll { find, replace, .. } => {
                if !content.contains(*find) {
                    if content.contains(*replace) {
                        return (content.to_string(), TransformResult::AlreadyApplied);
                    }
                    return (content.to_string(), TransformResult::NotMatched);
                }
                let result = content.replace(*find, *replace);
                (result, TransformResult::Applied)
            }

            Transform::Prepend { text, .. } => {
                if content.contains(*text) {
                    return (content.to_string(), TransformResult::AlreadyApplied);
                }
                (format!("{text}{content}"), TransformResult::Applied)
            }

            Transform::CommentOutLines { prefixes, .. } => {
                let mut any_changed = false;
                let mut lines: Vec<String> = Vec::new();
                for line in content.lines() {
                    let trimmed = line.trim();
                    if prefixes.iter().any(|p| trimmed.starts_with(p))
                        && !trimmed.starts_with("// [codex-codemod]")
                    {
                        lines.push(format!("// [codex-codemod] {line}"));
                        any_changed = true;
                    } else {
                        lines.push(line.to_string());
                    }
                }
                if !any_changed {
                    return (content.to_string(), TransformResult::AlreadyApplied);
                }
                let mut result = lines.join("\n");
                if content.ends_with('\n') {
                    result.push('\n');
                }
                (result, TransformResult::Applied)
            }

            Transform::Global { apply, .. } => {
                let result = apply(content, None);
                if result == content {
                    (content.to_string(), TransformResult::AlreadyApplied)
                } else {
                    (result, TransformResult::Applied)
                }
            }
        }
    }

    /// Apply this transform with a file path context (for Global transforms).
    pub fn apply_with_path(&self, content: &str, path: Option<&Path>) -> (String, TransformResult) {
        match self {
            Transform::Global { apply, .. } => {
                let result = apply(content, path);
                if result == content {
                    (content.to_string(), TransformResult::AlreadyApplied)
                } else {
                    (result, TransformResult::Applied)
                }
            }
            _ => self.apply(content),
        }
    }

    /// Short description for warning messages.
    pub fn description(&self) -> String {
        match self {
            Transform::ReplaceFile { path_suffix, .. } => {
                format!("ReplaceFile({path_suffix})")
            }
            Transform::StubModule { file_name } => {
                format!("StubModule({file_name})")
            }
            Transform::ReplaceFirst {
                path_suffix, find, ..
            } => {
                let short = truncate(find, 60);
                format!("ReplaceFirst({path_suffix}, \"{short}\")")
            }
            Transform::ReplaceAll {
                path_suffix, find, ..
            } => {
                let short = truncate(find, 60);
                format!("ReplaceAll({path_suffix}, \"{short}\")")
            }
            Transform::Prepend { path_suffix, .. } => {
                format!("Prepend({path_suffix})")
            }
            Transform::CommentOutLines { path_suffix, .. } => {
                format!("CommentOutLines({path_suffix})")
            }
            Transform::Global { name, .. } => {
                format!("Global({name})")
            }
        }
    }
}

/// Check if a file path ends with the given suffix (component-aware).
fn path_matches(path: &Path, suffix: &str) -> bool {
    let suffix_path = Path::new(suffix);
    path.ends_with(suffix_path)
}

/// Truncate a string for display.
fn truncate(s: &str, max: usize) -> String {
    let s = s.replace('\n', "\\n");
    if s.len() <= max {
        s
    } else {
        format!("{}...", &s[..max])
    }
}
